
#+Title: Tipos De Requerimientos

#+option: toc:nil

* Funcional 
Definición de los servicios que el sistema debe proporcionar, cómo debe reaccionar a una entrada particular y cómo se debe comportar ante situaciones particulares. los requerimientos se dividen en dos tipos principales:

- de usuario :: son declaraciones de los servicios que se espera que el sistema provea y de las restricciones bajos las cuales se debe operar.

- del sistema :: establecen con detalle los servicios y restricciones del sistema. 

* No funcionales
Son los que actúan para limitar la soluciones, se los conoce como restricciones o requisitos de calidad. A los requisitos no funcionales se los puede dividir en:

- Requisitos de producto :: Estos especifican el comportamiento del producto.

- Requisitos de organización :: Se derivan de políticas y procedimientos existentes en la organización del cliente y en la del desarrollador. 

- Requisitos externos :: Son los requisitos que derivan de los factores externos al sistemas y de su proceso de desarrollo, incluyen requerimientos de inseparabilidad que definen la manera en que el sistema interactúa con los otros sistemas de la organización. 

* FURPS+
Patrones de clasificación de requerimientos

- Facilidad de uso (Usability) :: Características, capacidades y algunos aspectos de seguridad, por ejemplo: se debe ver el texto fácilmente a una distancia de un metro

- Fiabilidad (reliability) :: Factores humanos (interacción), documentación, ayuda, etc, un ejemplo de este tipo de requerimiento sería: Si se produce algún fallo al usar un servicio externo solucionarlo localmente.

- Rendimiento (performance) :: Tiempo de respuesta, productividad, precisión, disponibilidad, use de los recursos. Ejemplo: Conseguir la autorización de pago en menos de 1 minuto el 90% de las veces. 

- Soporte (Supportability) :: Adaptabilidad, facilidad de mantenimiento, internacionalización, facilidad de recuperación de un fallo y grado de previsión. Ejemplo: el sistema debe ser instalable por los usuarios.

- Implementación (plus) :: Limitación de recursos, lenguajes y herramientas, hardware.

- Interfaz (plus) :: Restricciones impuestas para la interacción con sistemas externos (no es GUI).

- Operaciones (plus) :: Gestión del sistema, pautas administrativas, puesta en marcha.

- Empaquetamiento (plus) :: Forma de distribución.

- Legales (plus) :: Licencia, derechos de autor, etc. 
